#pragma once

#include "common_types.hpp"
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>
#include <cstdint>
#include <fstream>

namespace hft {
namespace hardware {

/**
 * FPGA / Hardware Bridge
 * 
 * Maps a PCIe BAR region (FPGA BRAM/Registers) to user-space memory.
 * Allows the CPU to read Order Books or Signals generated by the FPGA.
 * 
 * Hardware Layout (Hypothetical):
 * 0x0000: Control/Status Registers (CSR)
 * 0x1000: Order Book Snapshot (Bid/Ask Arrays)
 * 0x2000: Trade Engine Commands (FIFO)
 */
class HardwareBridge {
public:
    static constexpr size_t BAR_SIZE = 1024 * 1024 * 4; // 4MB
    static constexpr size_t TOB_OFFSET = 0x1000;

    struct alignas(64) HardwareTOB {
        uint64_t timestamp;
        double best_bid;
        double best_ask;
        uint32_t bid_qty;
        uint32_t ask_qty;
        uint64_t seq_num;
    };

    HardwareBridge() : bar_ptr_(nullptr), fd_(-1) {}

    ~HardwareBridge() {
        if (bar_ptr_) munmap((void*)bar_ptr_, BAR_SIZE);
        if (fd_ != -1) close(fd_);
    }

    bool init(const std::string& pci_resource_path) {
        fd_ = open(pci_resource_path.c_str(), O_RDWR | O_SYNC);
        if (fd_ < 0) return false;

        void* ptr = mmap(nullptr, BAR_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, fd_, 0);
        if (ptr == MAP_FAILED) {
            close(fd_);
            return false;
        }
        
        // Locked pointer
        bar_ptr_ = static_cast<volatile uint8_t*>(ptr);
        return true;
    }

    // Zero-Cost Read of FPGA State
    inline void read_tob(HardwareTOB& out) const {
        if (!bar_ptr_) return;
        
        // Volatile Cast to prevent compiler reordering/optimizing away the memory read
        const volatile HardwareTOB* hw_struct = reinterpret_cast<const volatile HardwareTOB*>(bar_ptr_ + TOB_OFFSET);
        
        // Copy fields (atomic guaranteed? depends on PCIe transaction width. usually 64-bit aligned is safe-ish)
        // Ideally we check a generation counter / sequence number before and after.
        
        uint64_t seq1 = hw_struct->seq_num;
        std::atomic_thread_fence(std::memory_order_acquire);
        
        out.timestamp = hw_struct->timestamp;
        out.best_bid = hw_struct->best_bid;
        out.best_ask = hw_struct->best_ask;
        out.bid_qty = hw_struct->bid_qty;
        out.ask_qty = hw_struct->ask_qty;
        
        std::atomic_thread_fence(std::memory_order_acquire);
        uint64_t seq2 = hw_struct->seq_num;
        
        if (seq1 != seq2) {
            // Torn read - retry or flag error
            // Simple spin retry
            return read_tob(out);
        }
    }

    // Send Command to FPGA Trade Engine
    inline void send_trigger(uint64_t order_id, double price, uint32_t qty, bool is_buy) {
        struct TriggerCmd {
            uint64_t signal_id;
            uint64_t price_fixed; // price * 1e8
            uint32_t qty;
            uint32_t flags; // bit 0 = buy/sell
        } cmd;
        
        cmd.signal_id = order_id;
        cmd.price_fixed = (uint64_t)(price * 100000000.0);
        cmd.qty = qty;
        cmd.flags = is_buy ? 1 : 0;
        
        // Write to FIFO command register at 0x2000
        volatile uint64_t* fifo = reinterpret_cast<volatile uint64_t*>(bar_ptr_ + 0x2000);
        
        // Write 64-bit chunks (PCIe TLP optimization)
        const uint64_t* src = reinterpret_cast<const uint64_t*>(&cmd);
        fifo[0] = src[0];
        fifo[1] = src[1]; 
        // Trigger register write to commit? assuming FIFO writes auto-push.
    }

private:
    volatile uint8_t* bar_ptr_;
    int fd_;
};

}
}
